///:~
/**
 * XRace V2
 * <p/>Use for ... ...
 * <p/>ID: $Id$
 * Last Commit:  $Author$
 * @version $Revision: $
 * 
 */
package com.sa.xrace.client.model;

import java.util.ArrayList;

import android.util.Log;

import com.sa.xrace.client.math.Point3f;
import com.sa.xrace.client.toolkit.ObjectPool;

/**
 * @author sliao
 * @version $Id$
 */
/**
 * This class is used to store the model data which is created by 3DS MAX.
 */
public final class t3DModel {
	/**
	 * 合成两个类 : Model t3DModel
	 */
	public int mModelID; // model's ID
    public int mType; // model's type
//    private t3DModel mModel; // keeping model's data
//    public Point3f mScale; // scale model on the x, y, z axis
//    private float mRadius; // for optimization

    public float mScale_x;
    public float mScale_y;
    public float mScale_z;
    
//    public void generate() {
//        mModel.generate();
//    }

    public void scale() {
        ObjectPool.gl.glScalef(mScale_x, mScale_y, mScale_z); // Scale the object on x, y
                                                   // and z axis
    }
    int numOfObjects; // number of objects
    int numOfMaterials; // number of material
    ArrayList<tMaterialInfo> Materials = new ArrayList<tMaterialInfo>(); // vectors keeping the materials
    public ArrayList<t3DObject> _3Dobjects = new ArrayList<t3DObject>(); // vectors keeping the objects
    // private Activity mainAcivity;

    public t3DModel(int modelID, int type,  Point3f scale) {
    	
//    	this.mModel = this;
        this.mModelID = modelID;
        this.mType = type;
        this.mScale_x = scale.x;
        this.mScale_y = scale.y;
        this.mScale_z = scale.z;
        Log.e("Mew t3DModel created","ID = "+modelID);
    	
//        this.Materials = new ArrayList<tMaterialInfo>();
//        this._3Dobjects = new ArrayList<t3DObject>();
        // this.mainAcivity = mainAcivity;
        // ObjectNumber.regNew(this);
    }

    /**
     * This function would generate all the buffer for render according those
     * data has been imported .
     */
    public void generate() {
    	for (t3DObject _3Dobject : _3Dobjects) {
            if (_3Dobject.materialID >= 0) {
                String strFilename = Materials.get(_3Dobject.materialID).strFile;
                if (strFilename != null && !"".equals(strFilename)) {
                    _3Dobject.loadBitmap(strFilename);
                }
            }
            _3Dobject.createBuffer();
        }
    }

    /**
     * This function would render all objects in the model with the buffer that
     * has been generated by function generate().
     */
    public void draw() {
//        if(mModelID == 2 && StateValuePool.counter != 0){
//            return;
//        }
//        if(mModelID == 2){
//            StateValuePool.counter ++;
//        }
//        Log.e("Number of 3Dobjects Wating to draw",""+_3Dobjects.size() + " Model ID" + mModelID);
        long start = System.currentTimeMillis();
        for(t3DObject _3Dobject : _3Dobjects){
            _3Dobject.draw();
        }
        Log.e("Finish draw"," Time " + mModelID + " " +(System.currentTimeMillis() - start));
    }

    public t3DObject getObject(String objectName) {
        for(t3DObject _3Dobject : _3Dobjects){
            if (_3Dobject.strName.equals(objectName)) {
                return _3Dobject;
            }
        }
        return null;
    }
    
    
    @Override
    protected void finalize() throws Throwable {
        Log.e("Object finalize",this.getClass().getName());
        super.finalize();
    }
}

/**
 * This class is used to keep the material data.
 */
class tMaterialInfo {
    String strName; // name of material
    String strFile; // texture's filename
    byte[] color = new byte[3];; // RGB color

//    public tMaterialInfo() {
//        
//    }

}